name: Sync with Replit

on:
  push:
    branches:
      - main

jobs:
  sync-replit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to Replit
        uses: JasonEtco/push-to-replit@v1
        with:
          replit_url: ${{ secrets.REPLIT_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
